### ISSUE TITLE
fyi: extracted firmware dump, etc

### ISSUE THREAD

**Issue by colemickens** [ncravino/H96_MAX_V58#1]
Hi, I've been experimenting with this box.

I hope to try collabora's rock5b u-boot on the h96 max v58 soon and see if I can get a modern u-boot booting. It should have USB support so it should be theoretically easy to get something up and running.

I have some notes, and a link to extracted firmware on my notes repo: https://github.com/colemickens/h96-max-v58-investigation

Feel free to close, just wanted to make sure you'd seen it. Maybe we can share notes as we progress.

**Comment by ncravino** [comment]
Damn for some reason I didn't receive a notification (thanks github!). That's great! I'll probably be taking another look at this box probably towards the end of this month. Although I was able to get its manufacturer Android to work closer to a proper Android TV set up, it stills has some quirks (and I'll probably end up using Linux anyway). That and I need to get a tiny blower fan in there, because I think it throttles under load (still have not debug this to check if it's not another issue).

**Comment by colemickens** [comment]
Just a note, but now that I've figured out how to force it into maskrom, I've been able to verify that mainline u-boot builds can boot the board. Granted, I haven't gotten it to actually support the network or USB yet, so I can't actually do a Linux install... but theoretically, someone with some u-boot or DTB experience should be able to take the extract DTB from the firmware that I've uploaded, port those changes to collabora's u-boot fork, or just mainline u-boot at this point and then we should be cooking with upstream plain old Linux.

I also in Germany, with my board, and its power supply is sitting in a basement in Kansas, so I have put this on the back burner. I also don't really know DTB stuffs well enough to properly hack on it.
